GET http://localhost:5280/printers
Accept: application/json
Authorization: Bearer 

###
GET http://localhost:5280/printers/3
Accept: application/json
Authorization: Bearer 

###
POST http://localhost:5280/printers
Content-Type: application/json
Accept: application/json
Authorization: Bearer 

{
  "brandId": 1,
  "modelName": "eStudio 3305",
  "isColorPrinter": false
}

###
PUT http://localhost:5280/printers/3
Content-Type: application/json
Accept: application/json
Authorization: Bearer 

{
  "brandId": 1,
  "modelName": "Test updated",
  "isColorPrinter": true
}

###
DELETE http://localhost:5280/printers/3
Content-Type: application/json
Accept: application/json
Authorization: Bearer 

### BRANDS --------------------------------------------------------------------------------
GET http://localhost:5280/brands
Content-Type: application/json
Accept: application/json

### CLIENTS
GET http://localhost:5280/clients
Content-Type: application/json
Accept: application/json
Authorization: Bearer 


###
GET http://localhost:5280/clients/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 

###
POST http://localhost:5280/clients
Content-Type: application/json
Accept: application/json
Authorization: Bearer 

{
  "document": "126772",
  "name": "TESTQ",
  "phone": "3949312119",
  "location": "Locccccation"
}

###
PUT http://localhost:5280/clients/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 


{
  "document": "326772",
  "name": "Cristian Pelaez",
  "phone": "3234567890",
  "location": "lasoidjasd"
}

###
DELETE http://localhost:5280/clients/6
Content-Type: application/json
Accept: application/json
Authorization: Bearer 

###
GET http://localhost:5280/clients/1/contracts
Content-Type: application/json
Accept: application/json
Authorization: Bearer 

###  CONTRACTS ------------------------------------------------------------------------
GET http://localhost:5280/contracts
Content-Type: application/json
Accept: application/json

###
GET http://localhost:5280/contracts/3
Content-Type: application/json
Accept: application/json

### 
POST http://localhost:5280/contracts
Content-Type: application/json
Accept: application/json
Authorization: Bearer 

{
  "clientId": 1,
  "printerId": 10,
  "blackCopyPrice": 300,
  "colorCopyPrice": 500,
  "minimumCharge": 400000,
  "startDate": "2026-06-19",
  "billDay": 19
}

###
PUT http://localhost:5280/contracts/4
Content-Type: application/json
Accept: application/json

{
  "isActive": true,
  "clientId": 1,
  "printerId": 1,
  "blackCopyPrice": 300,
  "colorCopyPrice": 500,
  "minimumCharge": 400000,
  "startDate": "2026-06-19",
  "billDay": 19
}

### 
DELETE http://localhost:5280/contracts/1
Content-Type: application/json
Accept: application/json

### MONTHLY READINGS -----------------------------------------------------------------
GET http://localhost:5280/monthly-readings/6

###
GET http://localhost:5280/contracts/3/readings

###
POST http://localhost:5280/monthly-readings
Content-Type: application/json
Accept: application/json

{
  "contractId": 4,
  "month": "2026-04",
  "blackCounter": 5000,
  "colorCounter": 3000,
  "notes":"adasdasdd"
}

###
PUT http://localhost:5280/contracts/3/readings/24
Content-Type: application/json
Accept: application/json

{
  "month": "2026-10",
  "blackCounter": 5500,
  "colorCounter": 3501,
  "notes":"adasdasdd"
}

###
DELETE http://localhost:5280/contracts/4/readings/18
Content-Type: application/json
Accept: application/json

{
  "contractId": 4,
  "month": "2026-04",
  "blackCounter": 5000,
  "colorCounter": 3000,
  "notes":"adasdasdd"
}

### AUTH -------------------------------------------------------------------------------------
POST http://localhost:5280/register
Content-Type: application/json
Accept: application/json

{
  "username": "testq",
  "password": "Pass123*"
}

###
POST http://localhost:5280/login
Content-Type: application/json
Accept: application/json

{
  "username": "test",
  "password": "Pass123*"
}

###
GET http://localhost:5280/me
Authorization: Bearer 